name: CI - ANGULAR - S3 - CLOUDFRONT
on:
    workflow_call:
      inputs:
        node_version:
          description: 'node version'
          required: true
          type: string
        environment:
          description: 'The environment to deploy to'
          required: true
          type: string
        env_vars_path:
          description: 'Path  terraform env vars'
          required: true
          type: string
        work_dir:
          description: Terraform work directory
          required: true
          type: string
      secrets:
        aws_access_key_id:
          description: 'AWS Access Key ID'
          required: true
        aws_secret_access_key:
          description: 'AWS Secret Access Key'
          required: true
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.aws_access_key_id }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_access_key }}
jobs:
  s3_cloudfront:
    runs-on: ubuntu-latest
    steps:
       - name: Checkout do repositorio
         uses: actions/checkout@v3
       - name: Setup Node
         uses: actions/setup-node@v1
         with:
           node-version: ${{ inputs.node_version }}
       - name: Install dependencies
         run: npm i
       - name: Check lint
         run: npm run lint:test
       - name: Check types
         run: npm run typecheck
       - name: Running tests
         run: npm run test:coverage
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ${{ inputs.work_dir }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.2.0"
      - name: Terraform init
        run: terraform init
      - name: Terraform Validate
        run: terraform validate