name: CI - ANGULAR - DOCKER - PORTAINER
on:
    workflow_call:
      inputs:
        node_version:
          description: 'node version'
          required: true
          type: string
jobs:
  docker_portainer:
    runs-on: ubuntu-latest
    steps:
       - name: Checkout do repositorio
         uses: actions/checkout@v1
       - name: Setup Node
         uses: actions/setup-node@v1
         with:
           node-version: ${{ inputs.node_version }}
       - name: Install dependencies
         run: npm i
       - name: Check lint
         run: npm run lint:test
       - name: Check types
         run: npm run typecheck
       - name: Running tests
         run: npm run test:coverage
