name: DEPLOY - LARAVEL - SERVERLESS
on:
  workflow_call:
    inputs:
      php_version:
          description: 'php version'
          required: true
          type: string
      run_migration:
        type: string
        default: 'false'
        description: Run migration into database
    secrets:
      aws_access_key_id:
        description: 'AWS Access Key ID'
        required: true
      aws_secret_access_key:
        description: 'AWS Secret Access Key'
        required: true
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.aws_access_key_id }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_access_key }}
jobs:
  serverless:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: ${{ inputs.php_version }}
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"
      - name: Install Composer Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Install Node Dependencies
        run: npm ci
      - name: Clear config
        run: php artisan config:clear
      - name: Deploy
        run: npx serverless deploy
      - name: Run migration
        run: npx serverless bref:cli --args="migrate --force"
        if: ${{inputs.run_migration == 'true'}}
