name: CI - NESTJS - SERVERLESS
on:
    workflow_call:
      inputs:
        node_version:
          description: 'node version'
          required: true
          type: string
        mysql_version:
          description: 'mysql version'
          required: true
          type: string
        mysql_db_name:
          description: 'mysql db name'
          required: true
          type: string
jobs:
  serverless:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: ${{inputs.mysql_version}}
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: ${{inputs.mysql_db_name}}
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{inputs.node_version}}
      - name: Install dependencies
        run: npm i
      - name: Update .env.test for CI
        run: sed -i 's|mysql://root:password@mysql:3306/${{inputs.mysql_db_name}}|mysql://root:password@localhost:3306/${{inputs.mysql_db_name}}|' .env.test
      - name: Running migrations
        run: npm run migrate:test
      - name: Typecheck
        run: npm run typecheck
      - name: Lint
        run: npm run lint:test
      - name: Coverage
        run: npm run test:coverage
      - name: Integration tests
        run: npm run test:integration