name: CI - PHP - LIB
on:
    workflow_call:
      inputs:
        php_version:
          description: 'php version'
          required: true
          type: string
jobs:
  php_lib:
    runs-on: ubuntu-latest
    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: ${{ inputs.php_version }}
    - uses: actions/checkout@v3
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Code style
      run: composer lint:test
    - name: Tests and coverage
      run: composer test:coverage