name: NEW - VERSION - PHP - LIB
on:
    workflow_call:
      secrets:
       git_token:
        description: 'token to use to create the tag'
        required: true
jobs:
  php_lib:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install jq
      run: sudo apt-get install -y jq
    - name: Get version from composer.json
      id: get_version
      run: |
        VERSION=$(jq -r '.version' composer.json)
        echo "::set-output name=version::$VERSION"
    - name: Create GitHub tag
      env:
        GITHUB_TOKEN: ${{ secrets.git_token }}
      run: |
        VERSION=v${{ steps.get_version.outputs.version }}
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git tag $VERSION
        git push origin v$VERSION