name: BUILD - AAB - REACT - NATIVE
on:
    workflow_call:
      inputs:
        node_version:
          description: 'node version'
          required: true
          type: string
        java_version:
          description: 'java version'
          required: true
          type: string
        env_content:
          description: 'Environment file content'
          required: true
          type: string
jobs:
  react_native:
    runs-on: ubuntu-latest
    steps:
       - name: Checkout
         uses: actions/checkout@v4
       - name: Set up JDK
         uses: actions/setup-java@v4
         with:
           distribution: 'temurin'
           java-version: ${{ inputs.java_version }}
       - name: Setup Node
         uses: actions/setup-node@v4
         with:
           node-version: ${{ inputs.node_version }}
       - name: Cache Node Modules
         uses: actions/cache@v4
         with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
       - name: Cache Gradle
         uses: actions/cache@v4
         with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
       - name: Install dependencies
         run: npm ci
       - name: Generate .env file
         run: echo "${{ inputs.env_content }}" > .env
       - name: Grant execute permission to Gradlew
         run: chmod +x android/gradlew
       - name: Build Release AAB
         run: cd android && ./gradlew bundleRelease --parallel --daemon --max-workers=4
       - name: Upload AAB
         uses: actions/upload-artifact@v4
         with:
           name: app-release-aab
           path: android/app/build/outputs/bundle/release/app-release.aab