name: CI - SPRING - BOOT - DOCKER - PORTAINER
on:
  workflow_call:
    inputs:
      node_version:
        description: 'node version'
        required: true
        type: string
      java_version:
        description: 'java version'
        required: true
        type: string
jobs:
  spring_boot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node_version }}
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ inputs.java_version }}
      - name: Install Java Dependencies
        run: npm run install:java:dependencies
      - name: Code style check
        run: npm run lint:test
      - name: Run tests and generate coverage report
        run: npm run test:pipeline
